### ISSUE TITLE
License clarification?

### ISSUE THREAD

**Issue by pombredanne** [zoom/viss#3]
Can you clarify the license of this repository? At the moment this utterly confusing and therefore completely unusable.

- Per https://github.com/zoom/viss/blob/a262924d7aec0f35b9b87dc8bcca8c6b27d4b8cb/package.json#L4 this is MIT.

- Per https://github.com/zoom/viss/blob/a262924d7aec0f35b9b87dc8bcca8c6b27d4b8cb/LICENSE#L1 this is GPL-3.0

- Per https://github.com/zoom/viss/blob/a262924d7aec0f35b9b87dc8bcca8c6b27d4b8cb/apps/calculator/static/specifications.md?plain=1#L10 there is yet another set of license for the spec.

**Comment by walter-carbajal** [comment]
@pombredanne thank you for raising this issue. we have modified the language so that it is clear that this project is licensed under GPL-3.0.

**Comment by pombredanne** [comment]
Thanks!

**Comment by pombredanne** [comment]
Note that while the GPL is a fine license for code, it may not be the best for the spec. You may want to consider something like a CC-BY or CC-BY-SA instead, or some GFDL license?
